spring:
  application:
    name: lovewith
  profiles:
    active: local #local,dev,real
  mvc:
    view: #view 경로 및 확장자 지정
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource: #DB 접속
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://175.126.73.243:3306/recommendin
    username: recommendin
    password: ekd09wkd
    hikari:
      connection-timeout: 30000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대시간을 설정 30초
      maximum-pool-size: 10 #최대 커넥션 개수 설정
      max-lifetime: 1800000 #커넥션 풀에서 살아있을 수 있는 커넥션의 최대 수명 시간 1,800초(30분)
  messages: #메시지
    basename: messages.validation
    encoding: UTF-8
  devtools: #View reload
    livereload:
      enabled: true
    restart: #컨트롤러, 모델단이 바뀌었을 때 프로젝트 재시작 설정(정확히는 classpath에 있는 모든 파일)
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB #파일 한 개당 최대 사이즈
      max-request-size: 200MB #요청당 최대 파일 크기
  mybatis:
    type-aliases-package: com.jworks.lovewith.vo # 필요한 경우 수정
    mapper-locations: com/jworks/lovewith/dao/*.xml
  redis:
    host: localhost # Redis 호스트
    port: 6379 # Redis 포트
    password: 1234 # Redis 비밀번호
  logging: #로그 지정
    level:
      '[com.jworks.lovewith]': debug
  server:
    port: 8000 #NGINX 설정 localhost 8080으로 접속
    servlet:
      encoding:
        charset: UTF-8
        enabled: true #http 인코딩 지원을 활성화할지 여부
        force: true